### ISSUE TITLE
What is a UML Diagram?

### ISSUE THREAD

**Issue by anaqvi72** [victoriarouton/Hermes#44]

**Comment by cindyherrera** [comment]
UML is an acronym for Unified Modeling Language and a UML diagram is based on this to visually represent a system. This system consists of actors, roles, actions, and classes to model and document software.

It can be used as a replacement for flowcharts.

There are two broad categories of UML diagrams: behavioral and structural. These will be further discussed as separate issues.


Resource Link:
https://tallyfy.com/uml-diagram/
