### ISSUE TITLE
Hand-Drawn UML Sequence Diagram of New User

### ISSUE THREAD

**Issue by cfulton5** [victoriarouton/Hermes#51]

**Comment by cfulton5** [comment]
[https://app.zenhub.com/files/336008019/d34e3047-28a4-4264-a725-28621063706f/download](https://app.zenhub.com/files/336008019/d34e3047-28a4-4264-a725-28621063706f/download)

**Comment by cindyherrera** [comment]
![newUser_sequenceDiagram.jpg](https://images.zenhubusercontent.com/601259e7adb9f70b35b93953/c8442d81-1ea9-4a75-b9a7-f2d5ecf8090c)

image from the first link mentioned in the previous comment
